### ISSUE TITLE
Incorrect url in the readme

### ISSUE THREAD

**Issue by MostHated** [Unity-Technologies/com.unity.performance-tracking#3]
Hey there,
    The readme says to add "git@github.com:Unity-Technologies/com.unity.performance-tracking.git" into the package manager, but that won't work unless you have an SSH key in the Unity organization and are granted access rights. For outside users, they need to put in "http://github.com/Unity-Technologies/com.unity.performance-tracking.git"

Thanks,
-MH

**Comment by jschmidt42** [comment]
@lochrist can you update that?
